config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :monuments, only: [:index, :show] do
    resources :bookings, only: [:create]
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: :show do
    resources :monuments, only:[:new, :create, :edit, :update]
  end

  resources :bookings, only: :destroy
  root to: 'pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  has_many :monuments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  validates :first_name, :last_name, :email, :password, presence: true
  # validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :email, uniqueness: true
  validates :first_name, uniqueness: { scope: :last_name }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    authorize current_user.monuments
    @bookings = current_user.bookings
    @review = Review.new
  end
end

app/views/users/edit.html.erb
<div class="login-container">
  <div class="card-form d-flex justify-content-center">
    <div class="rv-p">
      <div class="review-form">

        <%= simple_form_for current_user do |f| %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Changer ma photo", class: 'btn btn-primary' %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-space-between">
    <div class="col-xs-12.col-md-8">
      <div class="container" style="margin-top: 40px">
        <%= cl_image_tag current_user.profil, class: 'avatar avatar-large p-10' %>
        <h1> <%= current_user.full_name %> </h1>
        <%= link_to icon('fas', 'edit'), edit_user_path(current_user), class: 'edit'  %>
      </div>
    </div>
    <div class="col-xs-12.col-md-8" style="margin-top: 40px;margin-left: 10px;">
  <% if @bookings.empty? %>
    <div style="height: 20vh;">
      <h2>Vous n'avez pas de réservations pour l'instant...</h2>
      <%= link_to 'Réservez un monument !', monuments_path, class: 'btn btn-primary'  %>
    </div>
  <% else %>
    <h2 class="text-left">Mes reservations :</h2>
    <table class="Bookings table" class="text-center">
      <thead>
        <tr>
          <th scope="col">Monument</th>
          <th scope="col">Date de début</th>
          <th scope="col">Date de départ</th>
          <th scope="col">Durée du séjour</th>
          <th scope="col" colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @bookings.reverse.each do |booking| %>
          <tr>
            <td><%= booking.monument.name %></td>
            <td><%= booking.date_of_arrival %></td>
            <td><%= booking.date_of_departure %></td>
            <td><%= booking.duration %></td>

            <% if Date.today < booking.date_of_arrival %>
              <td><%= link_to 'Annule la reservation', booking, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-small btn-sm' %></td>
            <% else %>
            <td>
              <%= link_to 'Donne ton avis', new_monument_review_path(booking.monument.id), class: 'btn btn-outline-primary btn-sm'%>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

</div>
  </div>
</div>
<br>

  <% if current_user.monuments.empty? %>
    <div class="container-user-monument">

    <h2>Vous n'avez pas de monument pour l'instant ...</h2>
    <%= link_to 'Ajouter un monument', new_user_monument_path(current_user), class: 'example_d' %>
    </div>
  <% else %>
    <div class="container">
    <h2 class="text-left">Mes monuments :</h2>


    <div class="card-container">
      <% current_user.monuments.each do |monument| %>
        <%= render 'shared/monument_card', monument: monument %>
      <% end %>
    </div>
   <%= link_to 'Ajouter un monument', new_user_monument_path(current_user), class: 'example_d' %>
  </div>
  <% end %>

<br>
<br>
<br>
<br>
<br>