config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :monuments, only: [:index, :show] do
    resources :bookings, only: [:create]
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: :show do
    resources :monuments, only:[:new, :create, :edit, :update]
  end

  resources :bookings, only: :destroy
  root to: 'pages#home'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" id="sticky-footer">
  <div class="footer-links">
    <a href="https://github.com/FranckSiguier/rent_a_monument" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/p/CHxG6AhgNHq/?utm_source=ig_web_copy_link" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.youtube.com/watch?v=7Dbuc6vIRnE&ab_channel=Architecture" target="_blank"><i class="fab fa-youtube"></i></a>
  </div>
  <div class="footer-copyright">
    Rent a monument, pour les riches comme vous <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_monument_card.html.erb
<div class="card">
  <div class="info">
    <h4> <%= link_to monument.name.capitalize, monument_path(monument) %> </h4>
    <p> <%= monument.average %> <i class="fas fa-star"></i> </p>
  </div>
  <div id="carousel<%= monument.name.split(' ').join  %>" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% monument.photos.each_with_index do |photo, i| %>
        <% if i == 0 %>
          <div class="carousel-item active">
            <%= cl_image_tag photo.key, class: "text-center d-block w-100", alt:"First slide", crop: :fill%>
          </div>
        <% else %>
          <div class="carousel-item">
            <%= cl_image_tag photo.key , class: "text-center d-block w-100", alt: "slide number #{i + 1}", crop: :fill %>
          </div>
        <% end %>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carousel<%= monument.name.split(' ').join %>" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel<%= monument.name.split(' ').join  %>" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<!--       <div class="booking-info">
        <#% monument.bookings.each do |booking| %>
          <div class="booking-p d-flex justify-content-center">
            <h5><#%= booking.user.full_name %></h5>
            <p>arrival: <#%= booking.date_of_arrival %> </p>
            <p>departure: <#%= booking.date_of_departure %> </p>
          </div>
        <#% end %>
      </div> -->
</div>

app/views/shared/_monument_show.html.erb
<div class="monument-photos">
  <div id="carousel<%= monument.name.split(' ').join  %>" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% monument.photos.each_with_index do |photo, i| %>
        <% if i == 0 %>
          <div class="carousel-item active">
            <%= cl_image_tag photo.key, class: "text-center d-block w-100", alt:"First slide", crop: :fill%>
          </div>
        <% else %>
          <div class="carousel-item">
            <%= cl_image_tag photo.key , class: "text-center d-block w-100", alt: "slide number #{i + 1}", crop: :fill %>
          </div>
        <% end %>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carousel<%= monument.name.split(' ').join %>" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel<%= monument.name.split(' ').join  %>" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex align-item-center">
  <div class="logo-container d-flex">
    <ul class="navbar-nav mr-auto">
      <li>
        <%= link_to root_path do  %>
          <%= image_tag "logo.png", width: "60" %>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li style="margin-top: 5px; margin-left: 5px;">
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% end %>

    </ul>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Monuments", monuments_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to user_path(current_user) do  %>
              <%= cl_image_tag current_user.profil, class: "avatar" %>
            <% end %>
          </li>
      <% else %>
        <li class="nav-item d-flex">
           <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "Monuments", monuments_path, class: "nav-link" %>
        </li>
          <%= link_to "S'inscrire", new_user_registration_path, class: 'nav-link' %>
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sample.html.erb
<div class="container">
  <h1>Ce qui vous attend...</h1>
  <div class="content-home">
    <div class="cards-home">
      <% @monuments.sample(3).each do |monument| %>
        <%= link_to monument_path(monument), class: 'card-monument' do %>
            <div class="card-img">
              <%= image_tag cl_image_path monument.photos[0].key %>
            </div>
            <div class="card-info">
              <p><%= monument.name %></p>
              <p><%= monument.average %> <i class="fas fa-star"></i></p>
            </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>